config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'urls#index'
  get "/:short_url", to: "urls#show"
  get "shorty/:short_url", to: "urls#shorty", as: :shorty
  get 'urls/top'
  resources :urls, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord

  validates_presence_of :url, :access_count
  validates_format_of :url, with:  /\A(?:(?:http|https):\/\/)?([-a-zA-Z0-9.]{2,256}\.[a-z]{2,4})\b(?:\/[-a-zA-Z0-9@,!:%_\+.~#?&\/\/=]*)?\z/
  scope :top, -> (order, limit) { order(access_count: order).limit(limit) }
  ALPHABET = (('a'..'z').to_a + ('A'..'Z').to_a + (0..9).to_a).shuffle.join.freeze

  after_create :generate_short_url
  after_create :set_access

  def generate_short_url
    # use the bijective function to enconde the url
    self.short_url = self.bijective_encode(self.id)
    self.save
  end

  def find_duplicate
    u = Url.find_by_sanitize_url(self.sanitize_url)
  end

  def new_url?
    u = find_duplicate
    if u.blank?
      true
    else
      increase_count(u)
      false
    end
  end

  def set_access
    self.access_count = self.access_count + 1
    self.save
  end

  def increase_count(u)
    u.access_count += 1
    u.save!
  end

  def sanitize
    self.url.strip!
    self.sanitize_url = self.url.gsub(/(https?:\/\/)/, "")
    self.sanitize_url.slice!(-1) if self.sanitize_url[-1] == "/"
    self.sanitize_url = "http://#{self.sanitize_url}"
  end

  def bijective_encode(i)
    return ALPHABET[0] if i == 0
    s = ''
    base = ALPHABET.length
    while i > 0
      s << ALPHABET[i.modulo(base)]
      i /= base
    end
    s.reverse
  end

  def self.bijective_decode(s)
    i = 0
    base = ALPHABET.length
    s.each_char { |c| i = i * base + ALPHABET.index(c) }
    i
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
  class UrlsController < ApplicationController
    TOP_URL_DELIMITER = 100.freeze
    ORDER_DELIMITER = 'desc'.freeze
    before_action :find_shortened_url, only: [:show, :shorty]

    def index
      @url = Url.new
    end

    def show
      redirect_to @url.sanitize_url
    end

    def create
      @url = Url.new(url_params)
      @url.sanitize
      if @url.new_url?
        if @url.save
          flash[:success] = "Your url its shorter now" 
          redirect_to shorty_path(@url.short_url)
        else
          flash[:error] = "Something went wrong: #{@url.errors}" 
          render 'index'
        end
      else
        flash[:success] = 'We found that url in our records'
        redirect_to shorty_path(@url.find_duplicate.short_url)
      end
    end

    def shorty
      host = request.host_with_port
      @original_url = @url.sanitize_url
      @short_url = host + '/' + @url.short_url
    end

    def top
      @top_urls = Url.top(ORDER_DELIMITER, TOP_URL_DELIMITER)
    end


    private

    def find_shortened_url
      @url = Url.find(Url.bijective_decode(params[:short_url]))
    end

    def url_params
      params.require(:url).permit(:url)
    end
  end

app/helpers/alert_helper.rb
module AlertHelper
  def build_alert_classes(alert_type)
    classes = 'alert alert-dismissable '
    case alert_type.to_sym 
    when :alert, :danger, :error, :validation_errors
      classes += 'alert-danger'
    when :warning, :todo
      classes += 'alert-warning'
    when :notice, :success
      classes += 'alert-success'
    else 
      classes += 'alert-info'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shortys</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'shared/header'%>
  <div class="container">

    <div class="page-header" id="banner">
      <div class="row">
        <div class="col-lg-8 col-md-7 col-sm-6">
          <h1>Welcome To Shorty</h1>
        </div>
      </div>
      <div class="row">
        <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: build_alert_classes(type) %>
        <% end %>
        <%= yield %>
      </div>
    </div>

    <%= render partial: 'shared/footer'%>
  </div>

</body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-lg-12">
      <p>JhonnyC</a>.</p>

    </div>
  </div>

</footer>

app/views/shared/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Shortys", root_path, class: "navbar-brand"%>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <li>
            <%= link_to "Top Url's", urls_top_path %>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <%= link_to "GitHub Repository", "https://github.com/JhonnyM/shortys" %>
      </ul>

    </div>
  </div>
</div>

app/views/urls/index.html.erb
<div class="row">
  <div class="jumbotron">
    <h2>URL shortener</h2>
    <%= form_for @url do |f| %>
    <div class="form-group">
      <%= f.text_field :url, :class => "col-lg-6 control-label",  placeholder: "Enter the URL you want to shorten...", label: false  %>
    </div>
    <div class="form-group">
      <%= f.submit "Shortern" , :class => 'btn btn-warning' %>
    </div>
    <% end %>
  </div>
</div>

app/views/urls/shorty.html.erb
<h2>Well done, your link has been shortened!</h2>
<h3>Share it know, please copy the following url</h3>
<p>Your original url is: <%= @original_url %></p>
<p>Your Shortened url is: <%= @short_url %></p>

app/views/urls/top.html.erb
<h3>Top 100 accessed URL's</h3>
<% unless @top_urls.nil? %>
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>URL</th>
        <th>Count</th>
        <th>Short Url</th>
      </tr>
    </thead>
    <tbody>
    	<% @top_urls.each do |url| %>
      <tr>
        <td><%= url.sanitize_url %></td>
        <td><%= url.access_count %></td>
        <td><%= url.short_url %></td>
      </tr>
      <% end %>
    </tbody>
  </table> 
<% else %>
 <p>No information to display </p>
<% end %>